### ISSUE TITLE
Add endpoint for daily login reward progress

### ISSUE THREAD

**Issue by its-felix** [gw2-api/issues#18]
### Feature Description

Add an endpoint to query the current day of login rewards for the authenticated account.

Given this login reward progress:
![image](https://user-images.githubusercontent.com/23635466/147714768-9c0d3a6f-de95-4f44-bc63-8431225dea80.png)
the current day would be `17` (starting at `1`).

This addition would be useful for different kinds of applications:
- Crafting calculators could take Laurels and Mystic Coins into account (for example, if you'd get 8 Mystic Coins the next day, that could be mentioned as an information)
- When working towards a set goal of Laurels or Mystic Coins, applications using the API could calculate how many days you'd have to wait to get them passively

If possible, this endpoint could also return whether the reward has been collected today or not.

### Implementation

Suggested endpoint path: `/v2/dailylogin` (keeping the nameschema of  `/v2/dailycrafting`)
Suggested permissions: `account`, `progression`

### Example

```json
{
    "day": 17,
    "collected": false
}
```

**Comment by Archomeda** [comment]
Maybe extend this to include the id of the item that you get for that day? E.g. https://en.gw2treasures.com/item/68334?

**Comment by TheMrMilchmann** [comment]
Ideally, this would probably be delivered in two endpoints:
1. A static `/v2/dailylogin` endpoint should return general information about the login rewards. This would probably just be the item ID of the reward. A single item could look as follows (Note that `day` also serves as an ID for the endpoint in this example):
```json
{
    "day": 0,
    "reward": 12345
}
``` 

2. An authenticated endpoint `/v2/account/dailylogin` should return information about the current progress. Ideally, this would include whether the current daily login reward has been claimed yet:
```json
{
    "day": 12,
    "collected": false
}
```

This copies the style of the API for similar endpoints and (since there are not actually that many login rewards) the endpoints could also work independently.

I believe `collected` could be made to work similar to raid progress. That is, the flag would not actually tell whether the rewards of the current day are claimed, but the rewards of the last login date (`last_modified` of `/v2/account`).

**Comment by darthmaim** [comment]
Daily login rewards were replaced by the wizads vault, which does have API endpoints (even though those have some issues, see #78)
