### ISSUE TITLE
Prophet Shards and Crystals haven't been updated

### ISSUE THREAD

**Issue by IceQuote** [gw2-api/issues#43]
All Prophet Shards/Crystals still have their pre-EOD-descriptions and red crystals/shards have been removed from the game.

**Comment by queicherius** [comment]
Similar issue now with all old dungeon currencies

**Comment by darthmaim** [comment]
I'm guessing this issue is about currencies removed from the game not being removed from the API? The descriptions look correct to me.

I have created a new issue for this: #91

If this was not what the issue was about, please create a new issue using our issue template and include a clear description (expected vs. actual) and a reproduction.
