### ISSUE TITLE
Sun-Grown pistol

### ISSUE THREAD

**Issue by FullStuff** [gw2-api/issues#88]
### Current Behavior

The sun-grown pistol API seems not working as intended

Skin_wiki : https://wiki.guildwars2.com/index.php?title=Sun-Grown_Pistol_(skin)
Skin_API : https://api.guildwars2.com/v2/skins?ids=11555&lang=en

Item_wiki : https://wiki.guildwars2.com/wiki/Sun-Grown_Pistol
Item_API : https://api.guildwars2.com/v2/items?ids=99912&lang=en

Both API link return "all ids provided are invalid" for multiple ID link or "no such id" for the direct link
The wiki could give me the wrong ID but I cant verify it

### Expected Behavior

A valid JSON

### Steps To Reproduce

clic here : https://api.guildwars2.com/v2/skins?ids=11555&lang=en
or here : https://api.guildwars2.com/v2/skins/11555?lang=en

click here https://api.guildwars2.com/v2/items?ids=99912&lang=en
or here : https://api.guildwars2.com/v2/items/99912?lang=en

### Happening since

No idea

**Comment by darthmaim** [comment]
Sadly this is kinda expected, because not all items/skins are whitelisted in the API. Some items or skins are only available in the API for a short time before they get removed again for some unknown reason.

You can verify this for example on https://gw2treasures.com/item/99912, which tracks all items available in the API. You can see the item was in the API 362 days ago, and then got removed again on the same day.

It seems we don't have an issue tracking the issue of items being removed from the whitelist, I will create a separate more general issue describing this in more detail soon.
